"""Machine Learning Validation & Evidence Streamlit page.

The page separates four kinds of proof:

1. the controlling model-comparison evidence used for champion metrics;
2. same-sample PCA, K-Means, DBSCAN, and LOF evidence generated by Package 1;
3. historical course artifacts retained for audit only; and
4. governed downloads with source, time, threshold, and evidence labels.

No offline metric is presented as live production performance.
"""

from __future__ import annotations

# STREAMLIT CLOUD PATH BOOTSTRAP
# Streamlit executes page files from inside the app folder.
# Add the repository root so imports such as `app.*` and `src.*`
# work consistently locally and on Streamlit Community Cloud.
import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parent

while (
    _PROJECT_ROOT != _PROJECT_ROOT.parent
    and not (_PROJECT_ROOT / "src").is_dir()
):
    _PROJECT_ROOT = _PROJECT_ROOT.parent

if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))


import json
from pathlib import Path
from typing import Any

import pandas as pd
import plotly.express as px
import streamlit as st

from app.app_utils import (
    format_percent,
    get_best_threshold,
    get_champion_metrics,
    get_champion_model_name,
    load_model_selection_tables,
)
from app.ui.components import (
    inject_product_css,
    render_chart_header,
    render_detail_cards,
    render_empty_state,
    render_evidence_chart,
    render_kpi_grid,
    render_page_header,
    render_section_header,
    render_source_note,
    show_table_with_download,
)
from app.ui.design_system import CLUSTER_PALETTE, COLORS
from app.ui.ml_validation_visuals import (
    build_cluster_profile_heatmap,
    build_cluster_value_figure,
    build_dbscan_grid_figure,
    build_dbscan_k_distance_figure,
    build_kmeans_quality_figure,
    build_loading_heatmap,
    build_lof_deviation_figure,
    build_lof_feature_figure,
    build_lof_score_figure,
    build_outlier_comparison_figure,
    build_parallel_profile_figure,
    build_pca_density_figure,
    build_projection_figure,
    build_scree_figure,
    first_existing_column,
)
from app.ui.plotly_style import apply_product_layout


st.set_page_config(
    page_title="Machine Learning Validation & Evidence",
    page_icon="📊",
    layout="wide",
)
inject_product_css()


# ---------------------------------------------------------------------------
# Governed evidence locations
# ---------------------------------------------------------------------------

MANIFEST_PATH = Path("reports/metadata/ml_validation_manifest.json")
KMEANS_GRID_PATH = Path("reports/tables/ml_validation_kmeans_grid.csv")
DBSCAN_GRID_PATH = Path("reports/tables/ml_validation_dbscan_grid.csv")
DBSCAN_K_DISTANCE_PATH = Path(
    "reports/tables/ml_validation_dbscan_k_distance.csv"
)
CLUSTER_BUSINESS_PATH = Path(
    "reports/tables/ml_validation_cluster_business_summary.csv"
)
LOF_FEATURE_PROFILE_PATH = Path(
    "reports/tables/ml_validation_lof_feature_profile.csv"
)
LOF_INVESTIGATION_PATH = Path(
    "reports/tables/ml_validation_lof_investigation.csv"
)


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------


def safe_float(value: object, fallback: float = 0.0) -> float:
    """Convert one value to float without breaking the page."""

    try:
        if pd.isna(value):
            return fallback
        return float(value)
    except (TypeError, ValueError):
        return fallback


@st.cache_data
def load_manifest() -> dict[str, Any]:
    """Load the Package 1 artifact manifest when available."""

    if not MANIFEST_PATH.exists():
        return {}
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


@st.cache_data
def load_optional_table(path_text: str) -> pd.DataFrame:
    """Read a precomputed Package 1 table without refitting any model."""

    path = Path(path_text)
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def boolish(value: object) -> bool | None:
    """Interpret common boolean representations without guessing blanks."""

    if pd.isna(value):
        return None
    if isinstance(value, bool):
        return value
    text = str(value).strip().lower()
    if text in {"true", "1", "yes", "y", "checked"}:
        return True
    if text in {"false", "0", "no", "n", "unchecked"}:
        return False
    return None


def select_model_row(data: pd.DataFrame, model_name: str) -> pd.Series:
    """Return the named model row from the controlling comparison table."""

    if data.empty or "model_name" not in data.columns:
        return pd.Series(dtype="object")

    names = data["model_name"].astype(str).str.strip()
    exact = data.loc[names.str.casefold().eq(model_name.strip().casefold())]
    if not exact.empty:
        return exact.iloc[0]

    contains = data.loc[
        names.str.casefold().str.contains(
            model_name.strip().casefold(),
            regex=False,
        )
    ]
    return contains.iloc[0] if not contains.empty else pd.Series(dtype="object")


def best_metric_row(data: pd.DataFrame, score_column: str) -> pd.Series:
    """Return the strongest row for one numeric score column."""

    if data.empty or score_column not in data.columns:
        return pd.Series(dtype="object")
    scores = pd.to_numeric(data[score_column], errors="coerce")
    if scores.dropna().empty:
        return pd.Series(dtype="object")
    return data.loc[scores.idxmax()]


def build_model_comparison_figure(
    data: pd.DataFrame,
    champion_name: str,
):
    """Compare the selected champion with deployable and experimental models."""

    required = {"model_name", "pr_auc"}
    if data.empty or not required.issubset(data.columns):
        return None

    chart_data = data.copy()
    chart_data["pr_auc"] = pd.to_numeric(
        chart_data["pr_auc"],
        errors="coerce",
    )
    chart_data = chart_data.dropna(subset=["pr_auc"])
    if chart_data.empty:
        return None

    def status(row: pd.Series) -> str:
        name = str(row["model_name"])
        if name.casefold() == champion_name.casefold():
            return "Selected champion"
        deployable = boolish(row.get("deployable"))
        if deployable is False:
            return "Experimental / non-deployable"
        if "existing" in name.casefold() or "legacy" in name.casefold():
            return "Legacy benchmark"
        return "Deployable alternative"

    chart_data["Selection status"] = chart_data.apply(status, axis=1)
    chart_data = chart_data.sort_values("pr_auc", ascending=True).tail(12)

    hover_data: dict[str, Any] = {}
    for column in [
        "best_threshold",
        "best_precision",
        "best_recall",
        "best_f1_score",
        "roc_auc",
        "deployable",
    ]:
        if column in chart_data.columns:
            hover_data[column] = (
                ":.3f"
                if column not in {"deployable"}
                else True
            )

    figure = px.bar(
        chart_data,
        x="pr_auc",
        y="model_name",
        color="Selection status",
        orientation="h",
        color_discrete_map={
            "Selected champion": COLORS["positive"],
            "Deployable alternative": COLORS["brand"],
            "Experimental / non-deployable": COLORS["information"],
            "Legacy benchmark": COLORS["neutral"],
        },
        hover_data=hover_data,
        text="pr_auc",
    )
    figure.update_traces(texttemplate="%{text:.4f}", textposition="outside")
    figure.update_xaxes(title_text="Precision–recall area under curve")
    figure.update_yaxes(title_text="Candidate model")
    return apply_product_layout(
        figure,
        height=570,
        legend_title="Selection status",
    )


def build_coverage_figure(data: pd.DataFrame):
    """Summarise validation coverage without presenting it as performance."""

    if data.empty:
        return None

    status_column = first_existing_column(
        data,
        [
            "status",
            "coverage_status",
            "implementation_status",
            "implemented",
        ],
    )
    if status_column:
        chart_data = (
            data[status_column]
            .astype(str)
            .value_counts()
            .rename_axis("Status")
            .reset_index(name="Rows")
        )
    else:
        topic_column = first_existing_column(
            data,
            ["method_family", "topic", "learning_day", "method"],
        )
        if topic_column is None:
            return None
        chart_data = (
            data[topic_column]
            .astype(str)
            .value_counts()
            .rename_axis("Status")
            .reset_index(name="Rows")
        )

    figure = px.bar(
        chart_data.sort_values("Rows"),
        x="Rows",
        y="Status",
        orientation="h",
        text="Rows",
        color="Status",
        color_discrete_sequence=CLUSTER_PALETTE,
    )
    figure.update_traces(textposition="outside")
    figure.update_layout(showlegend=False)
    figure.update_xaxes(title_text="Evidence rows")
    figure.update_yaxes(title_text="Validation status or area")
    return apply_product_layout(figure, height=430)


def pca_component_cards(
    variance: pd.DataFrame,
    loadings: pd.DataFrame,
) -> list[tuple[str, str, str]]:
    """Explain each PCA axis from its strongest positive and negative loading."""

    if variance.empty or loadings.empty or "feature" not in loadings.columns:
        return []

    ratio_column = first_existing_column(
        variance,
        ["explained_variance_ratio", "variance_ratio"],
    )
    cards: list[tuple[str, str, str]] = []

    for component in ["PC1", "PC2", "PC3"]:
        if component not in loadings.columns:
            continue
        values = pd.to_numeric(loadings[component], errors="coerce")
        if values.dropna().empty:
            continue
        positive_index = values.idxmax()
        negative_index = values.idxmin()
        positive_feature = str(loadings.loc[positive_index, "feature"])
        negative_feature = str(loadings.loc[negative_index, "feature"])
        positive_value = safe_float(values.loc[positive_index])
        negative_value = safe_float(values.loc[negative_index])

        ratio = 0.0
        if ratio_column and "component" in variance.columns:
            match = variance.loc[
                variance["component"].astype(str).eq(component),
                ratio_column,
            ]
            if not match.empty:
                ratio = safe_float(match.iloc[0])

        cards.append(
            (
                component,
                f"{ratio:.1%} of sampled variation",
                (
                    f"Positive direction: {positive_feature} "
                    f"({positive_value:+.2f}). Negative direction: "
                    f"{negative_feature} ({negative_value:+.2f})."
                ),
            )
        )

    return cards


def choose_cluster_value_metric(
    data: pd.DataFrame,
) -> tuple[str | None, str, bool]:
    """Choose the strongest available business-value metric honestly."""

    candidates = [
        ("purchase_rate", "Observed purchase rate", True),
        (
            "avg_purchase_intent_score",
            "Average purchase-intent score",
            False,
        ),
        ("avg_cart_share", "Average cart-event share", True),
    ]
    for column, label, is_rate in candidates:
        if column not in data.columns:
            continue
        values = pd.to_numeric(data[column], errors="coerce")
        if values.notna().any():
            return column, label, is_rate
    return None, "Unavailable", False


def build_cluster_action_table(
    business: pd.DataFrame,
    profile: pd.DataFrame,
) -> pd.DataFrame:
    """Create transparent, rule-based cluster test suggestions.

    The output is not a persona generator. Every action is linked to a visible
    metric rule so the user can audit why the suggestion was produced.
    """

    if business.empty or "cluster" not in business.columns:
        return pd.DataFrame()

    actions = business.copy()
    profile_wide = pd.DataFrame()
    if not profile.empty:
        profile_wide = profile.pivot_table(
            index="cluster",
            columns="feature",
            values="standardized_mean",
            aggfunc="mean",
        )

    value_column, value_label, _ = choose_cluster_value_metric(actions)
    value_values = (
        pd.to_numeric(actions[value_column], errors="coerce")
        if value_column
        else pd.Series(index=actions.index, dtype=float)
    )
    value_median = safe_float(value_values.median())
    cart_median = safe_float(
        pd.to_numeric(actions.get("avg_cart_share"), errors="coerce").median()
    )
    view_median = safe_float(
        pd.to_numeric(actions.get("avg_view_share"), errors="coerce").median()
    )

    rows: list[dict[str, Any]] = []
    for _, row in actions.iterrows():
        cluster = int(row["cluster"])
        dominant_feature = "Unavailable"
        dominant_value = 0.0
        if not profile_wide.empty and cluster in profile_wide.index:
            cluster_profile = pd.to_numeric(
                profile_wide.loc[cluster],
                errors="coerce",
            )
            if cluster_profile.notna().any():
                dominant_feature = str(cluster_profile.abs().idxmax())
                dominant_value = safe_float(
                    cluster_profile.loc[dominant_feature]
                )

        value = safe_float(row.get(value_column)) if value_column else 0.0
        cart = safe_float(row.get("avg_cart_share"))
        view = safe_float(row.get("avg_view_share"))

        if value_column and value >= value_median and cart >= cart_median:
            action = "Test conversion-focused offers with an incremental-lift holdout."
            rule = f"Above-median {value_label.lower()} and cart share."
        elif cart >= cart_median and value_column and value < value_median:
            action = "Test cart-recovery and checkout-friction interventions."
            rule = f"Above-median cart share but below-median {value_label.lower()}."
        elif view >= view_median and cart < cart_median:
            action = "Test product-discovery-to-cart nurture before using discounts."
            rule = "Above-median view share with below-median cart share."
        else:
            action = "Use a low-cost differentiated message and measure response."
            rule = "No stronger conversion or cart-friction rule was triggered."

        rows.append(
            {
                "cluster": cluster,
                "visitor_count": int(row.get("visitor_count", 0)),
                "visitor_share": safe_float(row.get("visitor_share")),
                value_label: value if value_column else None,
                "dominant_standardized_behaviour": dominant_feature,
                "dominant_behaviour_z": dominant_value,
                "analytical_test_suggestion": action,
                "rule_basis": rule,
            }
        )

    return pd.DataFrame(rows).sort_values("cluster").reset_index(drop=True)


def investigation_label(row: pd.Series) -> str:
    """Create one readable selectbox label for a flagged visitor."""

    identity = row.get("visitorid", row.get("sample_row_id", "NA"))
    rank = int(safe_float(row.get("investigation_rank"), 0))
    score = safe_float(row.get("lof_score"))
    severity = str(row.get("lof_severity", "Unknown"))
    return f"#{rank} · visitor {identity} · LOF {score:.2f} · {severity}"


# ---------------------------------------------------------------------------
# Load controlling and same-sample evidence
# ---------------------------------------------------------------------------


tables = load_model_selection_tables()
manifest = load_manifest()

final_comparison = tables.get("final_true_champion_comparison", pd.DataFrame())
final_summary = tables.get("final_true_champion_summary", pd.DataFrame())
final_thresholds = tables.get("final_true_champion_thresholds", pd.DataFrame())
final_stability = tables.get("final_true_champion_stability", pd.DataFrame())
final_sensitivity = tables.get("final_true_champion_sensitivity", pd.DataFrame())
coverage = tables.get("mvd_coverage_matrix", pd.DataFrame())
historical_kmeans = tables.get("mvd_kmeans_summary", pd.DataFrame())
historical_dbscan = tables.get("mvd_dbscan_summary", pd.DataFrame())
historical_lof = tables.get("mvd_lof_summary", pd.DataFrame())
outlier_comparison = tables.get("mvd_outlier_comparison", pd.DataFrame())

pca_variance = tables.get("ml_validation_pca_variance", pd.DataFrame())
pca_loadings = tables.get("ml_validation_pca_loadings", pd.DataFrame())
projection = tables.get("ml_validation_projection", pd.DataFrame())
cluster_profile = tables.get("ml_validation_cluster_profile", pd.DataFrame())
method_summary = tables.get("ml_validation_method_summary", pd.DataFrame())

kmeans_grid = load_optional_table(str(KMEANS_GRID_PATH))
dbscan_grid = load_optional_table(str(DBSCAN_GRID_PATH))
dbscan_k_distance = load_optional_table(str(DBSCAN_K_DISTANCE_PATH))
cluster_business = load_optional_table(str(CLUSTER_BUSINESS_PATH))
lof_feature_profile = load_optional_table(str(LOF_FEATURE_PROFILE_PATH))
lof_investigation = load_optional_table(str(LOF_INVESTIGATION_PATH))

if pca_variance.empty:
    pca_variance = tables.get("mvd_pca_variance", pd.DataFrame())

champion_name = get_champion_model_name()
active_threshold = get_best_threshold()
fallback_metrics = get_champion_metrics()
champion_row = select_model_row(final_comparison, champion_name)
summary_row = (
    final_summary.iloc[0]
    if not final_summary.empty
    else pd.Series(dtype="object")
)

# The named row in the controlling comparison table is always preferred. The
# alternate summary is used only as an explicit resilience fallback when that
# row is unavailable; it is never silently mixed into the comparison chart.
metric_row = champion_row if not champion_row.empty else summary_row
metric_source = (
    "reports/tables/final_true_champion_comparison.csv"
    if not champion_row.empty
    else "reports/tables/final_true_champion_summary.csv"
)
metric_basis = (
    "Controlling comparison row"
    if not champion_row.empty
    else "Explicit alternate-summary fallback"
)

pr_auc = safe_float(
    metric_row.get("pr_auc", fallback_metrics.get("pr_auc", 0))
)
f1_score = safe_float(
    metric_row.get(
        "best_f1_score",
        metric_row.get("f1_score", fallback_metrics.get("best_f1_score", 0)),
    )
)
precision = safe_float(
    metric_row.get(
        "best_precision",
        metric_row.get("precision", fallback_metrics.get("best_precision", 0)),
    )
)
recall = safe_float(
    metric_row.get(
        "best_recall",
        metric_row.get("recall", fallback_metrics.get("best_recall", 0)),
    )
)
comparison_threshold = safe_float(
    metric_row.get("best_threshold", active_threshold),
    active_threshold,
)

sample_rows = int(manifest.get("sample_rows", len(projection))) if manifest else len(projection)
source_rows = int(manifest.get("source_rows", sample_rows)) if manifest else sample_rows
generated_at = str(
    manifest.get("generated_at_utc", "Existing project evidence")
)
evidence_type = str(
    manifest.get("evidence_type", "offline analytical evidence")
)
parameters = manifest.get("parameters", {}) if manifest else {}
selected_k = int(parameters.get("kmeans_k", 5))
selected_eps = safe_float(parameters.get("dbscan_eps", 1.0), 1.0)
selected_min_samples = int(parameters.get("dbscan_min_samples", 5))
lof_threshold = safe_float(parameters.get("lof_score_threshold", 0.0))

first_three_variance = 0.0
if not pca_variance.empty:
    cumulative_column = first_existing_column(
        pca_variance,
        ["cumulative_explained_variance", "cumulative_variance"],
    )
    ratio_column = first_existing_column(
        pca_variance,
        ["explained_variance_ratio", "variance_ratio", "explained_variance"],
    )
    if cumulative_column:
        first_three_variance = safe_float(
            pca_variance.iloc[min(2, len(pca_variance) - 1)][
                cumulative_column
            ]
        )
    elif ratio_column:
        first_three_variance = float(
            pd.to_numeric(
                pca_variance[ratio_column],
                errors="coerce",
            ).head(3).sum()
        )


# ---------------------------------------------------------------------------
# Page identity
# ---------------------------------------------------------------------------

st.sidebar.markdown("## ML Validation & Evidence")
st.sidebar.caption("Offline analytical validation and project proof")
st.sidebar.markdown("---")
st.sidebar.markdown(f"**Champion:** {champion_name}")
st.sidebar.markdown(f"**Active threshold:** {active_threshold:.2f}")
st.sidebar.markdown(f"**Evidence sample:** {sample_rows:,} visitors")
st.sidebar.markdown(f"**Source rows:** {source_rows:,}")
st.sidebar.markdown("---")
st.sidebar.caption(
    "The page separates same-sample analytical evidence, historical audit "
    "tables, and active model metadata."
)

render_page_header(
    eyebrow="Machine learning assurance",
    title="Machine Learning Validation & Evidence",
    subtitle=(
        "See exactly how the active model compares, how behaviour is reduced "
        "and clustered, and which visitors look locally unusual."
    ),
    badges=[
        (f"Champion: {champion_name}", "positive"),
        (f"Active threshold: {active_threshold:.2f}", "info"),
        ("Offline analytical evidence", "warning"),
    ],
)

render_kpi_grid(
    [
        (
            "Selected champion",
            champion_name,
            "Active deployable model from the controlling comparison table.",
        ),
        (
            "Comparison PR-AUC / F1",
            f"{pr_auc:.3f} / {f1_score:.3f}",
            f"{metric_basis}; source: {Path(metric_source).name}.",
        ),
        (
            "First 3 PCA components",
            format_percent(first_three_variance),
            "Behaviour variation retained in the same-sample 3D projection.",
        ),
        (
            "Visual evidence sample",
            f"{sample_rows:,}",
            "Deterministic visitors used across PCA, clustering, and LOF.",
        ),
    ]
)

(
    overview_tab,
    pca_tab,
    kmeans_tab,
    dbscan_tab,
    lof_tab,
    evidence_tab,
) = st.tabs(
    [
        "Overview",
        "PCA Intelligence",
        "K-Means",
        "DBSCAN",
        "LOF",
        "Evidence Library",
    ]
)


# ---------------------------------------------------------------------------
# Overview
# ---------------------------------------------------------------------------

with overview_tab:
    render_section_header(
        "Model assurance",
        "How the deployable champion compares",
        (
            "The chart separates the active champion, deployable alternatives, "
            "experimental candidates, and legacy evidence."
        ),
    )
    model_figure = build_model_comparison_figure(
        final_comparison,
        champion_name,
    )
    highest_row = best_metric_row(final_comparison, "pr_auc")
    highest_name = str(highest_row.get("model_name", "Unavailable"))
    highest_pr_auc = safe_float(highest_row.get("pr_auc"))
    highest_deployable = boolish(highest_row.get("deployable"))

    if highest_name and highest_name.casefold() != champion_name.casefold():
        deployability_text = (
            "marked non-deployable"
            if highest_deployable is False
            else "not the active champion"
        )
        comparison_finding = (
            f"{champion_name} is the active champion at PR-AUC {pr_auc:.4f}, "
            f"F1 {f1_score:.4f}, precision {precision:.1%}, and recall "
            f"{recall:.1%} at threshold {comparison_threshold:.2f}. "
            f"{highest_name} has the highest raw PR-AUC ({highest_pr_auc:.4f}) "
            f"but is {deployability_text}."
        )
    else:
        comparison_finding = (
            f"{champion_name} is both the active champion and the strongest "
            f"PR-AUC candidate at {pr_auc:.4f}, with F1 {f1_score:.4f} at "
            f"threshold {comparison_threshold:.2f}."
        )

    render_chart_header(
        "How does the deployable champion compare with all candidates?",
        (
            "Longer bars mean stronger rare-buyer ranking. Colour explains "
            "why raw PR-AUC alone does not define deployment status."
        ),
    )
    if not render_evidence_chart(
        figure=model_figure,
        key="mlv_model_comparison",
        what_it_shows=(
            "Candidate models ranked by PR-AUC from the controlling comparison table."
        ),
        how_to_read=(
            "Compare bar length first, then use selection status to distinguish "
            "deployable, experimental, and legacy candidates."
        ),
        actual_finding=comparison_finding,
        conclusion=(
            "The selected model is an operational decision supported by ranking, "
            "deployability, threshold behaviour, and stability—not PR-AUC alone."
        ),
        recommended_action=(
            "Keep the active champion until a deployable challenger beats it in "
            "the same controlled evaluation and passes monitored rollout gates."
        ),
        limitation=(
            "All values are offline validation evidence and must not be described "
            "as mature live production performance."
        ),
        source="reports/tables/final_true_champion_comparison.csv",
        evidence_type="controlling offline model-comparison evidence",
        refreshed_at=generated_at,
        source_extra=(
            f"Displayed KPI basis: {metric_basis}. Metric source: {metric_source}."
        ),
    ):
        render_empty_state(
            "Model comparison evidence is unavailable",
            "The controlling champion comparison table could not be loaded.",
            "Regenerate the final champion evidence before using this section.",
        )

    render_section_header(
        "Validation coverage",
        "What the project has demonstrated",
        (
            "Coverage is an audit trail. It is not a substitute for calculation, "
            "visual, or production-quality evidence."
        ),
    )
    coverage_figure = build_coverage_figure(coverage)
    render_chart_header(
        "How much documented validation evidence exists?",
        "Bars count governed evidence rows by their documented status.",
    )
    render_evidence_chart(
        figure=coverage_figure,
        key="mlv_coverage",
        what_it_shows=(
            "The number of project evidence rows by validation status or area."
        ),
        how_to_read=(
            "Each bar counts documentation rows; it is not a model-performance metric."
        ),
        actual_finding=(
            f"The current audit table contains {len(coverage):,} documented rows."
        ),
        conclusion=(
            "The platform retains a traceable evidence trail beyond the deployed model."
        ),
        recommended_action=(
            "Use the Evidence Library for technical audit while keeping executive "
            "pages focused on decisions."
        ),
        limitation=(
            "Coverage quantity does not prove calculation correctness, visual "
            "quality, or production readiness."
        ),
        source="reports/tables/mvd_method_coverage_matrix.csv",
        evidence_type="historical project coverage evidence",
        refreshed_at="Existing project artifact",
    )


# ---------------------------------------------------------------------------
# PCA
# ---------------------------------------------------------------------------

with pca_tab:
    render_section_header(
        "Dimensionality reduction",
        "PCA behaviour landscape",
        (
            "The same deterministic visitor sample is projected into three "
            "components before clustering and anomaly review."
        ),
    )

    if projection.empty:
        render_empty_state(
            "Interactive PCA evidence has not been generated",
            "The same-sample projection table is missing.",
            "Run: python3 -m src.visualization.build_ml_validation_evidence",
        )
    else:
        control_1, control_2, control_3 = st.columns([0.22, 0.38, 0.40])
        with control_1:
            dimension = st.radio(
                "View",
                ["3D", "2D"],
                horizontal=True,
                key="pca_dimension",
            )
        with control_2:
            color_choice = st.selectbox(
                "Colour visitors by",
                ["kmeans_cluster", "dbscan_cluster", "lof_severity"],
                format_func=lambda value: {
                    "kmeans_cluster": "K-Means cluster",
                    "dbscan_cluster": "DBSCAN cluster",
                    "lof_severity": "LOF severity",
                }[value],
                key="pca_colour",
            )
        with control_3:
            max_points = st.slider(
                "Maximum displayed visitors",
                min_value=1_000,
                max_value=min(8_000, max(1_000, len(projection))),
                value=min(5_000, max(1_000, len(projection))),
                step=500,
                key="pca_max_points",
            )

        render_chart_header(
            "How does visitor behaviour separate in reduced space?",
            (
                "Rotate the 3D view or switch to 2D. Colour changes the analytical "
                "overlay without changing PCA geometry."
            ),
        )
        pca_figure = build_projection_figure(
            projection,
            color_column=color_choice,
            dimension=dimension,
            max_points=max_points,
        )
        render_evidence_chart(
            figure=pca_figure,
            key="mlv_pca_projection",
            what_it_shows=(
                "A two- or three-dimensional projection of standardized visitor behaviours."
            ),
            how_to_read=(
                "Nearby points behave similarly. Separation suggests structure; "
                "overlap means behaviour is shared."
            ),
            actual_finding=(
                f"The first three components retain {first_three_variance:.1%} "
                f"of variation across the {sample_rows:,}-visitor evidence sample."
            ),
            conclusion=(
                "PCA is useful for visual exploration, but cluster meaning must "
                "come from original feature profiles."
            ),
            recommended_action=(
                "Use the projection to locate structure, then validate every "
                "interpretation with loadings and cluster profiles."
            ),
            limitation=(
                "PCA is linear and distance in this chart is not purchase probability."
            ),
            source="reports/tables/ml_validation_projection_sample.csv",
            evidence_type=evidence_type,
            refreshed_at=generated_at,
            source_extra=f"Displayed from {source_rows:,} source visitor rows.",
        )

        show_pca_diagnostics = st.checkbox(
            "Show PCA density, variance, and feature-direction evidence",
            value=False,
            key="show_pca_diagnostics",
            help=(
                "Supporting charts are precomputed and opened only when needed "
                "to keep the first view calm."
            ),
        )
        if show_pca_diagnostics:
            render_section_header(
                "Density evidence",
                "Where visitors concentrate in the PCA plane",
                (
                    "Density contours reveal overlap that a point cloud can hide."
                ),
            )
            density_figure = build_pca_density_figure(projection)
            pc1_range = safe_float(
                pd.to_numeric(projection.get("PC1"), errors="coerce").max()
                - pd.to_numeric(projection.get("PC1"), errors="coerce").min()
            )
            pc2_range = safe_float(
                pd.to_numeric(projection.get("PC2"), errors="coerce").max()
                - pd.to_numeric(projection.get("PC2"), errors="coerce").min()
            )
            render_evidence_chart(
                figure=density_figure,
                key="mlv_pca_density",
                what_it_shows=(
                    "Concentration of visitors across PC1 and PC2, with a small "
                    "deterministic point overlay."
                ),
                how_to_read=(
                    "Warmer contours contain more visitors. Sparse outer regions "
                    "deserve separate anomaly or segment review."
                ),
                actual_finding=(
                    f"The sampled projection spans {pc1_range:.2f} units on PC1 "
                    f"and {pc2_range:.2f} units on PC2."
                ),
                conclusion=(
                    "Density shows where the typical behaviour mass sits and where "
                    "low-density visitors begin."
                ),
                recommended_action=(
                    "Use dense regions for broad segment interpretation and inspect "
                    "sparse regions with DBSCAN and LOF before acting."
                ),
                limitation=(
                    "The contour is a two-dimensional view and can hide separation "
                    "that exists on PC3 or later components."
                ),
                source="reports/tables/ml_validation_projection_sample.csv",
                evidence_type=evidence_type,
                refreshed_at=generated_at,
            )

            render_section_header(
                "Variance evidence",
                "How much information each component preserves",
            )
            scree_figure = build_scree_figure(pca_variance)
            component_values = pd.to_numeric(
                pca_variance.get("explained_variance_ratio"),
                errors="coerce",
            ).dropna()
            component_text = ", ".join(
                f"PC{index + 1} {value:.1%}"
                for index, value in enumerate(component_values.head(3))
            )
            render_evidence_chart(
                figure=scree_figure,
                key="mlv_pca_scree",
                what_it_shows=(
                    "Explained variance for each PCA component and cumulative retention."
                ),
                how_to_read=(
                    "Bars show each component's contribution; the line shows how "
                    "quickly total retained variation accumulates."
                ),
                actual_finding=(
                    f"{component_text}. Together they retain "
                    f"{first_three_variance:.1%}."
                ),
                conclusion=(
                    "Three components provide a compact visual summary for this "
                    "feature set."
                ),
                recommended_action=(
                    "Use all three for exploration, then return to original features "
                    "for campaign or risk decisions."
                ),
                limitation=(
                    "Explained variance measures mathematical retention, not business value."
                ),
                source="reports/tables/ml_validation_pca_variance.csv",
                evidence_type=evidence_type,
                refreshed_at=generated_at,
            )

            render_section_header(
                "Feature contribution",
                "What creates the PCA directions",
                (
                    "Positive and negative loadings show which original behaviours "
                    "shape each component."
                ),
            )
            loading_figure = build_loading_heatmap(pca_loadings)
            loading_rows = len(pca_loadings)
            render_evidence_chart(
                figure=loading_figure,
                key="mlv_pca_loadings",
                what_it_shows=(
                    "The direction and strength of each original feature in PC1-PC3."
                ),
                how_to_read=(
                    "Large absolute values have stronger influence; signs indicate "
                    "opposite directions within the same component."
                ),
                actual_finding=(
                    f"The loading table compares {loading_rows:,} behaviour features "
                    "across three components."
                ),
                conclusion=(
                    "Component meaning is credible only when tied back to these "
                    "original behaviours."
                ),
                recommended_action=(
                    "Use the strongest positive and negative loadings when naming "
                    "component directions."
                ),
                limitation=(
                    "A strong loading is a mathematical contribution, not causal proof."
                ),
                source="reports/tables/ml_validation_pca_loadings.csv",
                evidence_type=evidence_type,
                refreshed_at=generated_at,
            )

            cards = pca_component_cards(pca_variance, pca_loadings)
            if cards:
                render_detail_cards(cards)


# ---------------------------------------------------------------------------
# K-Means
# ---------------------------------------------------------------------------

with kmeans_tab:
    render_section_header(
        "Partitioning intelligence",
        "K-Means customer structure",
        (
            "The active projection, elbow grid, profiles, and value evidence "
            "all use the same deterministic sample."
        ),
    )

    if projection.empty:
        render_empty_state(
            "K-Means projection is unavailable",
            "The same-sample clustering projection has not been generated.",
            "Run: python3 -m src.visualization.build_ml_validation_evidence",
        )
    else:
        dimension = st.radio(
            "Projection view",
            ["3D", "2D"],
            horizontal=True,
            key="kmeans_dimension",
        )
        render_chart_header(
            "Where are the selected K-Means visitor groups?",
            (
                "Colours show clusters and labelled diamonds show centroids. "
                "The selected k comes from the same-sample 3/5/7 comparison."
            ),
        )
        figure = build_projection_figure(
            projection,
            color_column="kmeans_cluster",
            dimension=dimension,
            max_points=min(6_000, len(projection)),
        )
        selected_k_row = kmeans_grid.loc[
            pd.to_numeric(kmeans_grid.get("k"), errors="coerce").eq(
                selected_k
            )
        ] if not kmeans_grid.empty else pd.DataFrame()
        selected_silhouette = (
            safe_float(selected_k_row.iloc[0].get("silhouette_score"))
            if not selected_k_row.empty
            else 0.0
        )
        cluster_count = (
            projection["kmeans_cluster"].nunique()
            if "kmeans_cluster" in projection.columns
            else 0
        )
        render_evidence_chart(
            figure=figure,
            key="mlv_kmeans_projection",
            what_it_shows=(
                "Visitor groups created by distance to K-Means centroids in "
                "standardized behaviour space."
            ),
            how_to_read=(
                "Separated colour clouds indicate stronger distinction; overlap "
                "indicates boundary visitors with similar behaviour."
            ),
            actual_finding=(
                f"The same-sample selection uses k={selected_k}, producing "
                f"{cluster_count} displayed clusters with silhouette "
                f"{selected_silhouette:.3f}."
            ),
            conclusion=(
                "K-Means creates a complete partition, but original feature and "
                "value profiles determine whether the groups are useful."
            ),
            recommended_action=(
                "Use cluster-specific tests only after reviewing profile, size, "
                "and value evidence below."
            ),
            limitation=(
                "K-Means forces every visitor into one compact group, including "
                "uncertain boundary cases."
            ),
            source="reports/tables/ml_validation_projection_sample.csv",
            evidence_type=evidence_type,
            refreshed_at=generated_at,
            source_extra=(
                f"Selected parameters are recorded in {MANIFEST_PATH}."
            ),
        )

        show_kmeans_support = st.checkbox(
            "Show K-Means elbow, profile, parallel, and value evidence",
            value=False,
            key="show_kmeans_support",
        )
        if show_kmeans_support:
            render_section_header(
                "Selection evidence",
                "Choosing the number of K-Means clusters",
                (
                    "The elbow uses k=1-10. Selection is restricted to the required "
                    "k=3, 5, and 7 candidates on the same sample."
                ),
            )
            quality_figure = build_kmeans_quality_figure(
                kmeans_grid,
                selected_k=selected_k,
            )
            tested_k = (
                int(pd.to_numeric(kmeans_grid.get("k"), errors="coerce").nunique())
                if not kmeans_grid.empty
                else 0
            )
            render_evidence_chart(
                figure=quality_figure,
                key="mlv_kmeans_quality",
                what_it_shows=(
                    "Inertia for k=1-10 and silhouette for valid multi-cluster candidates."
                ),
                how_to_read=(
                    "Look for diminishing inertia improvement and stronger silhouette; "
                    "the selected candidate is highlighted."
                ),
                actual_finding=(
                    f"The same-sample grid tests {tested_k} k values and selects "
                    f"k={selected_k} from the required 3/5/7 candidates with "
                    f"silhouette {selected_silhouette:.3f}."
                ),
                conclusion=(
                    "The selected k balances compactness, separation, and a cluster "
                    "count that remains explainable."
                ),
                recommended_action=(
                    "Retest the grid after feature or population changes before "
                    "reusing cluster labels."
                ),
                limitation=(
                    "Internal metrics do not guarantee stable or commercially useful groups."
                ),
                source="reports/tables/ml_validation_kmeans_grid.csv",
                evidence_type=evidence_type,
                refreshed_at=generated_at,
                source_extra=(
                    f"Silhouette uses at most {manifest.get('metric_rules', {}).get('silhouette_sample_rows', 'NA')} deterministic rows."
                ),
            )

            render_section_header(
                "Behaviour profile",
                "How each cluster differs from the average visitor",
                (
                    "Heatmap cells are standardized means; parallel lines show the "
                    "same evidence across every feature."
                ),
            )
            profile_figure = build_cluster_profile_heatmap(cluster_profile)
            profile_cluster_count = (
                cluster_profile["cluster"].nunique()
                if "cluster" in cluster_profile.columns
                else 0
            )
            profile_feature_count = (
                cluster_profile["feature"].nunique()
                if "feature" in cluster_profile.columns
                else 0
            )
            render_evidence_chart(
                figure=profile_figure,
                key="mlv_kmeans_profile",
                what_it_shows=(
                    "Standardized feature means for every selected K-Means cluster."
                ),
                how_to_read=(
                    "Positive cells are above the sample mean; negative cells are below it."
                ),
                actual_finding=(
                    f"The profile compares {profile_cluster_count} clusters across "
                    f"{profile_feature_count} behaviour features."
                ),
                conclusion=(
                    "Cluster meaning comes from original behaviour differences, not "
                    "from PCA location alone."
                ),
                recommended_action=(
                    "Name clusters only after identifying their strongest above- and "
                    "below-average behaviours."
                ),
                limitation=(
                    "Cluster averages hide within-group variation and boundary visitors."
                ),
                source="reports/tables/ml_validation_cluster_profile.csv",
                evidence_type=evidence_type,
                refreshed_at=generated_at,
            )

            parallel_figure = build_parallel_profile_figure(cluster_profile)
            render_chart_header(
                "Which clusters follow genuinely different behaviour paths?",
                (
                    "Each line is one cluster profile across all standardized features."
                ),
            )
            render_evidence_chart(
                figure=parallel_figure,
                key="mlv_kmeans_parallel",
                what_it_shows=(
                    "The selected cluster profiles across the complete standardized feature set."
                ),
                how_to_read=(
                    "Lines that diverge strongly on a feature indicate a meaningful "
                    "behaviour difference; similar lines indicate weak differentiation."
                ),
                actual_finding=(
                    f"The parallel view compares {profile_cluster_count} cluster lines "
                    f"across {profile_feature_count} shared dimensions."
                ),
                conclusion=(
                    "A cluster is actionable only when its line differs on behaviours "
                    "that support a different test or treatment."
                ),
                recommended_action=(
                    "Prioritise the features with the clearest line separation when "
                    "designing cluster-specific experiments."
                ),
                limitation=(
                    "Parallel coordinates show cluster means, not individual visitor spread."
                ),
                source="reports/tables/ml_validation_cluster_profile.csv",
                evidence_type=evidence_type,
                refreshed_at=generated_at,
            )

            value_column, value_label, value_is_rate = choose_cluster_value_metric(
                cluster_business
            )
            value_figure = (
                build_cluster_value_figure(
                    cluster_business,
                    value_column=value_column,
                    value_label=value_label,
                    value_is_rate=value_is_rate,
                )
                if value_column
                else None
            )
            best_value_row = (
                cluster_business.loc[
                    pd.to_numeric(
                        cluster_business[value_column],
                        errors="coerce",
                    ).idxmax()
                ]
                if value_column
                and not cluster_business.empty
                and pd.to_numeric(
                    cluster_business[value_column],
                    errors="coerce",
                ).notna().any()
                else pd.Series(dtype="object")
            )
            best_value_cluster = best_value_row.get("cluster", "NA")
            best_value = safe_float(best_value_row.get(value_column))
            value_text = (
                f"{best_value:.1%}"
                if value_is_rate
                else f"{best_value:.3f}"
            )
            render_chart_header(
                "How do cluster size and verified value evidence compare?",
                (
                    "Bars show population share; the line uses the strongest available "
                    "observed value metric without inventing revenue."
                ),
            )
            render_evidence_chart(
                figure=value_figure,
                key="mlv_kmeans_value",
                what_it_shows=(
                    f"Visitor share and {value_label.lower()} for each selected cluster."
                ),
                how_to_read=(
                    "Large clusters create reach; the line shows whether the available "
                    "value evidence is stronger or weaker."
                ),
                actual_finding=(
                    f"Cluster {best_value_cluster} has the highest {value_label.lower()} "
                    f"at {value_text}."
                ),
                conclusion=(
                    "Cluster size and value should be considered together before "
                    "allocating campaign or investigation effort."
                ),
                recommended_action=(
                    "Use controlled tests rather than assuming the highest-value cluster "
                    "will respond to every intervention."
                ),
                limitation=(
                    "The chart uses the best available observed metric; it is not "
                    "incremental revenue or causal lift."
                ),
                source="reports/tables/ml_validation_cluster_business_summary.csv",
                evidence_type=evidence_type,
                refreshed_at=generated_at,
            )

            action_table = build_cluster_action_table(
                cluster_business,
                cluster_profile,
            )
            show_table_with_download(
                label="Rule-based cluster test suggestions",
                data=action_table,
                file_name="ml_cluster_test_suggestions.csv",
                metadata={
                    "generated_at": generated_at,
                    "evidence_type": evidence_type,
                    "sample_rows": str(sample_rows),
                },
                description=(
                    "Every suggestion shows its rule basis. These are analytical "
                    "test ideas, not deployed personas or causal recommendations."
                ),
            )


# ---------------------------------------------------------------------------
# DBSCAN
# ---------------------------------------------------------------------------

with dbscan_tab:
    render_section_header(
        "Density intelligence",
        "DBSCAN cluster and noise landscape",
        (
            "The projection, k-distance curve, and complete 3x3 parameter grid "
            "use the same deterministic visitor sample."
        ),
    )

    if projection.empty:
        render_empty_state(
            "DBSCAN projection is unavailable",
            "The same-sample density projection has not been generated.",
            "Run: python3 -m src.visualization.build_ml_validation_evidence",
        )
    else:
        dimension = st.radio(
            "Projection view",
            ["3D", "2D"],
            horizontal=True,
            key="dbscan_dimension",
        )
        render_chart_header(
            "Which visitors belong to dense regions, borders, or noise?",
            (
                "Colour identifies the density group. Marker shape distinguishes "
                "core, border, and noise observations."
            ),
        )
        figure = build_projection_figure(
            projection,
            color_column="dbscan_cluster",
            dimension=dimension,
            symbol_column="dbscan_point_type",
            max_points=min(6_000, len(projection)),
        )
        noise_count = int(
            (projection.get("dbscan_point_type", pd.Series(dtype=str)) == "Noise").sum()
        )
        noise_rate = noise_count / len(projection) if len(projection) else 0
        cluster_count = (
            projection.loc[
                projection.get(
                    "dbscan_cluster",
                    pd.Series(dtype=str),
                ).astype(str)
                != "-1",
                "dbscan_cluster",
            ].nunique()
            if "dbscan_cluster" in projection.columns
            else 0
        )
        selected_dbscan_row = (
            dbscan_grid.loc[
                pd.to_numeric(dbscan_grid.get("eps"), errors="coerce").eq(
                    selected_eps
                )
                & pd.to_numeric(
                    dbscan_grid.get("min_samples"),
                    errors="coerce",
                ).eq(selected_min_samples)
            ]
            if not dbscan_grid.empty
            else pd.DataFrame()
        )
        selected_dbscan_silhouette = (
            safe_float(
                selected_dbscan_row.iloc[0].get(
                    "silhouette_score_no_noise"
                )
            )
            if not selected_dbscan_row.empty
            else 0.0
        )
        render_evidence_chart(
            figure=figure,
            key="mlv_dbscan_projection",
            what_it_shows=(
                "Density clusters, boundary observations, and visitors outside dense neighbourhoods."
            ),
            how_to_read=(
                "Core points sit inside dense regions, borders sit near edges, and "
                "noise does not satisfy the selected density rule."
            ),
            actual_finding=(
                f"The selected same-sample setting eps={selected_eps:g}, "
                f"min_samples={selected_min_samples} finds {cluster_count} clusters "
                f"and {noise_count:,} noise visitors ({noise_rate:.1%}), with "
                f"non-noise silhouette {selected_dbscan_silhouette:.3f}."
            ),
            conclusion=(
                "DBSCAN exposes irregular density and uncertainty that K-Means must "
                "force into a group."
            ),
            recommended_action=(
                "Review noise composition before using it as an anomaly, quality, or "
                "exclusion signal."
            ),
            limitation=(
                "DBSCAN is sensitive to scaling, epsilon, minimum samples, and unequal density."
            ),
            source="reports/tables/ml_validation_projection_sample.csv",
            evidence_type=evidence_type,
            refreshed_at=generated_at,
            source_extra=(
                "Selection rule and complete grid are recorded in the Package 1 manifest."
            ),
        )

        show_dbscan_support = st.checkbox(
            "Show DBSCAN k-distance and complete 3x3 parameter evidence",
            value=False,
            key="show_dbscan_support",
        )
        if show_dbscan_support:
            render_section_header(
                "Neighbour-distance evidence",
                "Where the selected epsilon sits on the k-distance curve",
                (
                    "The curve sorts each visitor's distance to the selected neighbour rank."
                ),
            )
            k_distance_figure = build_dbscan_k_distance_figure(
                dbscan_k_distance,
                selected_eps=selected_eps,
            )
            distance_values = pd.to_numeric(
                dbscan_k_distance.get("k_distance"),
                errors="coerce",
            ).dropna()
            p90_distance = safe_float(distance_values.quantile(0.90))
            p95_distance = safe_float(distance_values.quantile(0.95))
            render_evidence_chart(
                figure=k_distance_figure,
                key="mlv_dbscan_k_distance",
                what_it_shows=(
                    "Sorted distance to the selected neighbour rank for the same sample."
                ),
                how_to_read=(
                    "The curve's bend is a diagnostic region; the dashed line shows "
                    "the selected epsilon, not an automatically proven optimum."
                ),
                actual_finding=(
                    f"The selected epsilon is {selected_eps:g}. The exported curve's "
                    f"90th and 95th percentile distances are {p90_distance:.3f} and "
                    f"{p95_distance:.3f}."
                ),
                conclusion=(
                    "The selected radius should be judged together with cluster count, "
                    "noise rate, and stability across the grid."
                ),
                recommended_action=(
                    "Rebuild the curve after feature scaling or population changes "
                    "before reusing epsilon."
                ),
                limitation=(
                    "A k-distance bend is partly visual and does not guarantee business-useful clusters."
                ),
                source="reports/tables/ml_validation_dbscan_k_distance.csv",
                evidence_type=evidence_type,
                refreshed_at=generated_at,
            )

            render_section_header(
                "Parameter sensitivity",
                "How epsilon and minimum samples change quality and noise",
                (
                    "The heatmaps cover the required eps 0.5/1.0/2.0 × "
                    "min_samples 3/5/10 grid on one sample."
                ),
            )
            grid_figure = build_dbscan_grid_figure(
                dbscan_grid,
                selected_eps=selected_eps,
                selected_min_samples=selected_min_samples,
            )
            valid_grid = dbscan_grid.loc[
                pd.to_numeric(
                    dbscan_grid.get("silhouette_score_no_noise"),
                    errors="coerce",
                ).notna()
            ] if not dbscan_grid.empty else pd.DataFrame()
            best_grid_row = best_metric_row(
                valid_grid,
                "silhouette_score_no_noise",
            )
            render_evidence_chart(
                figure=grid_figure,
                key="mlv_dbscan_grid",
                what_it_shows=(
                    "Non-noise silhouette, noise rate, and cluster count for all nine required parameter combinations."
                ),
                how_to_read=(
                    "Use the left heatmap for separation and the right for excluded "
                    "share. The square marks the guarded selected setting."
                ),
                actual_finding=(
                    f"All {len(dbscan_grid):,} required combinations were evaluated. "
                    f"The highest raw silhouette is {safe_float(best_grid_row.get('silhouette_score_no_noise')):.3f} "
                    f"at eps={best_grid_row.get('eps', 'NA')} and min_samples="
                    f"{best_grid_row.get('min_samples', 'NA')}; the selected guarded "
                    f"setting is eps={selected_eps:g}, min_samples={selected_min_samples}."
                ),
                conclusion=(
                    "Parameter choice is a trade-off: a raw maximum can create too "
                    "many clusters or an operationally weak noise share."
                ),
                recommended_action=(
                    "Use the guarded setting for exploration and retest stability on "
                    "future data before operational use."
                ),
                limitation=(
                    "Silhouette excludes noise and can favour settings that are not "
                    "commercially meaningful."
                ),
                source="reports/tables/ml_validation_dbscan_grid.csv",
                evidence_type=evidence_type,
                refreshed_at=generated_at,
                source_extra=(
                    "Exactly nine same-sample combinations; no historical grid is mixed into this chart."
                ),
            )


# ---------------------------------------------------------------------------
# Local Outlier Factor
# ---------------------------------------------------------------------------

with lof_tab:
    render_section_header(
        "Local anomaly intelligence",
        "LOF unusual-behaviour landscape",
        (
            "LOF compares each visitor with nearby behavioural neighbours in the "
            "same standardized feature space."
        ),
    )

    if projection.empty:
        render_empty_state(
            "LOF projection is unavailable",
            "The same-sample anomaly projection has not been generated.",
            "Run: python3 -m src.visualization.build_ml_validation_evidence",
        )
    else:
        dimension = st.radio(
            "Projection view",
            ["3D", "2D"],
            horizontal=True,
            key="lof_dimension",
        )
        render_chart_header(
            "Where are the strongest local deviations?",
            (
                "Colour shows severity and capped marker size reflects LOF score. "
                "Warmer points deserve earlier review, not automatic punishment."
            ),
        )
        figure = build_projection_figure(
            projection,
            color_column="lof_severity",
            dimension=dimension,
            size_column="lof_score",
            max_points=min(6_000, len(projection)),
        )
        outlier_mask = pd.to_numeric(
            projection.get("lof_outlier", 0),
            errors="coerce",
        ).fillna(0).astype(bool)
        outlier_count = int(outlier_mask.sum())
        outlier_rate = outlier_count / len(projection) if len(projection) else 0
        highest_score = safe_float(
            pd.to_numeric(
                projection.get("lof_score", pd.Series([0])),
                errors="coerce",
            ).max()
        )
        render_evidence_chart(
            figure=figure,
            key="mlv_lof_projection",
            what_it_shows=(
                "Visitors whose local behavioural density differs from nearby observations."
            ),
            how_to_read=(
                "Higher scores and warmer severity indicate stronger local deviation, "
                "not automatic fraud or bad behaviour."
            ),
            actual_finding=(
                f"LOF flags {outlier_count:,} of {len(projection):,} same-sample "
                f"visitors ({outlier_rate:.1%}); the highest score is {highest_score:.2f}."
            ),
            conclusion=(
                "LOF creates a prioritised investigation queue for behaviour that "
                "global rules can miss."
            ),
            recommended_action=(
                "Review high-severity visitors with feature deviations and business "
                "context before taking action."
            ),
            limitation=(
                "The contamination setting controls the flagged share and unusual "
                "does not mean harmful."
            ),
            source="reports/tables/ml_validation_projection_sample.csv",
            evidence_type=evidence_type,
            refreshed_at=generated_at,
        )

        show_lof_support = st.checkbox(
            "Show LOF score, feature-deviation, and investigation evidence",
            value=False,
            key="show_lof_support",
        )
        if show_lof_support:
            render_section_header(
                "Score evidence",
                "How strongly flagged visitors differ from normal visitors",
                (
                    "The log scale preserves both the common score range and extreme tail."
                ),
            )
            lof_figure = build_lof_score_figure(
                projection,
                threshold=lof_threshold if lof_threshold > 0 else None,
            )
            normal_scores = pd.to_numeric(
                projection.loc[~outlier_mask, "lof_score"],
                errors="coerce",
            ).dropna()
            flagged_scores = pd.to_numeric(
                projection.loc[outlier_mask, "lof_score"],
                errors="coerce",
            ).dropna()
            normal_median = safe_float(normal_scores.median())
            flagged_median = safe_float(flagged_scores.median())
            render_evidence_chart(
                figure=lof_figure,
                key="mlv_lof_distribution",
                what_it_shows=(
                    "LOF score distributions for normal and algorithm-flagged visitors."
                ),
                how_to_read=(
                    "Farther right means stronger local deviation. The dashed line "
                    "marks the same-sample flag threshold."
                ),
                actual_finding=(
                    f"Median LOF is {normal_median:.2f} for normal visitors and "
                    f"{flagged_median:.2f} for flagged visitors; the flag threshold "
                    f"is {lof_threshold:.2f}."
                ),
                conclusion=(
                    "The score supplies investigation priority while contamination "
                    "defines queue size."
                ),
                recommended_action=(
                    "Review the highest-scoring cases first and recalibrate only when "
                    "investigation capacity or false-positive tolerance changes."
                ),
                limitation=(
                    "LOF scores are sample-relative and are not comparable across "
                    "unrelated feature spaces."
                ),
                source="reports/tables/ml_validation_projection_sample.csv",
                evidence_type=evidence_type,
                refreshed_at=generated_at,
                source_extra=(
                    f"Threshold recorded in {MANIFEST_PATH}."
                ),
            )

            render_section_header(
                "Feature deviation",
                "Which behaviours distinguish LOF outliers",
                (
                    "The chart compares average standardized behaviour for flagged "
                    "and normal visitors."
                ),
            )
            deviation_figure = build_lof_deviation_figure(lof_feature_profile)
            top_deviation = (
                lof_feature_profile.iloc[0]
                if not lof_feature_profile.empty
                else pd.Series(dtype="object")
            )
            render_evidence_chart(
                figure=deviation_figure,
                key="mlv_lof_deviation",
                what_it_shows=(
                    "Outlier mean minus normal mean for each standardized behaviour feature."
                ),
                how_to_read=(
                    "Positive bars are higher for outliers; negative bars are lower. "
                    "Length is the size of the standardized gap."
                ),
                actual_finding=(
                    f"The largest average gap is {top_deviation.get('feature', 'NA')} "
                    f"at {safe_float(top_deviation.get('standardized_gap')):+.2f} standard deviations."
                ),
                conclusion=(
                    "The flagged group has measurable behavioural differences that "
                    "can guide review order."
                ),
                recommended_action=(
                    "Use the strongest gaps to design investigation filters, then "
                    "validate them against confirmed outcomes."
                ),
                limitation=(
                    "Group averages can hide multiple outlier types and do not prove causality."
                ),
                source="reports/tables/ml_validation_lof_feature_profile.csv",
                evidence_type=evidence_type,
                refreshed_at=generated_at,
            )

            render_section_header(
                "Investigation drill-down",
                "Why one selected visitor looks unusual",
                (
                    "Choose a top-ranked LOF case and inspect its standardized feature deviations."
                ),
            )
            if not lof_investigation.empty:
                option_rows = lof_investigation.head(25).copy()
                options = option_rows.index.tolist()
                selected_index = st.selectbox(
                    "Top LOF investigation case",
                    options,
                    format_func=lambda index: investigation_label(
                        option_rows.loc[index]
                    ),
                    key="lof_investigation_case",
                )
                selected_row = option_rows.loc[selected_index]
                feature_figure = build_lof_feature_figure(selected_row)
                render_evidence_chart(
                    figure=feature_figure,
                    key="mlv_lof_selected_features",
                    what_it_shows=(
                        "The selected visitor's standardized distance from the sample "
                        "mean for every behaviour feature."
                    ),
                    how_to_read=(
                        "Bars to the right are above average and bars to the left are "
                        "below average. These are deviations, not SHAP contributions."
                    ),
                    actual_finding=(
                        f"Selected rank #{int(safe_float(selected_row.get('investigation_rank')))} "
                        f"has LOF {safe_float(selected_row.get('lof_score')):.2f}; its "
                        f"largest deviation is {selected_row.get('dominant_deviation_feature', 'NA')} "
                        f"at {safe_float(selected_row.get('dominant_deviation_z')):+.2f}σ."
                    ),
                    conclusion=(
                        "The drill-down explains what is unusual before a reviewer "
                        "decides whether the case matters."
                    ),
                    recommended_action=(
                        "Compare the selected case with event history and confirmed "
                        "outcomes before campaign, quality, or risk action."
                    ),
                    limitation=(
                        "Feature deviations are descriptive and are not additive model contributions."
                    ),
                    source="reports/tables/ml_validation_lof_investigation.csv",
                    evidence_type=evidence_type,
                    refreshed_at=generated_at,
                )

                preferred_columns = [
                    column
                    for column in [
                        "investigation_rank",
                        "visitorid",
                        "sample_row_id",
                        "lof_score",
                        "lof_severity",
                        "purchase_intent_score",
                        "purchased",
                        "dominant_deviation_feature",
                        "dominant_deviation_z",
                        "total_events",
                        "view_count",
                        "addtocart_count",
                        "unique_items",
                    ]
                    if column in lof_investigation.columns
                ]
                show_table_with_download(
                    label="LOF investigation queue",
                    data=lof_investigation[preferred_columns],
                    file_name="ml_lof_investigation_queue.csv",
                    metadata={
                        "generated_at": generated_at,
                        "evidence_type": evidence_type,
                        "sample_rows": str(sample_rows),
                    },
                    description=(
                        "Top same-sample cases only. The export is an investigation "
                        "queue, not a confirmed anomaly label."
                    ),
                )
            else:
                render_empty_state(
                    "LOF investigation evidence is unavailable",
                    "The governed top-outlier table is missing.",
                    "Regenerate Package 1 analytical evidence.",
                )

            comparison_figure = build_outlier_comparison_figure(
                outlier_comparison
            )
            if comparison_figure is not None:
                render_section_header(
                    "Historical method comparison",
                    "How prior outlier methods differ in flagged volume",
                    (
                        "This table is retained for audit and is not mixed with the "
                        "same-sample LOF calculation above."
                    ),
                )
                comparison_rate_column = first_existing_column(
                    outlier_comparison,
                    ["outlier_rate", "anomaly_rate"],
                )
                comparison_values = (
                    pd.to_numeric(
                        outlier_comparison[comparison_rate_column],
                        errors="coerce",
                    ).dropna()
                    if comparison_rate_column
                    else pd.Series(dtype=float)
                )
                render_evidence_chart(
                    figure=comparison_figure,
                    key="mlv_outlier_comparison",
                    what_it_shows=(
                        "Flagged-rate differences across historical anomaly methods."
                    ),
                    how_to_read=(
                        "Longer bars mean more observations were flagged; more flags "
                        "does not automatically mean better detection."
                    ),
                    actual_finding=(
                        f"The historical methods flag between "
                        f"{safe_float(comparison_values.min()):.1%} and "
                        f"{safe_float(comparison_values.max()):.1%} of their own evaluated rows."
                    ),
                    conclusion=(
                        "Different methods encode different definitions of unusual behaviour."
                    ),
                    recommended_action=(
                        "Compare overlap and confirmed outcomes before combining methods."
                    ),
                    limitation=(
                        "This historical comparison uses different row counts and is "
                        "not a same-sample precision comparison."
                    ),
                    source="reports/tables/mvd_outlier_method_comparison.csv",
                    evidence_type="historical project artifact",
                    refreshed_at="Existing project artifact",
                )


# ---------------------------------------------------------------------------
# Governed evidence library
# ---------------------------------------------------------------------------

with evidence_tab:
    render_section_header(
        "Technical evidence library",
        "Downloadable source tables",
        (
            "Same-sample Package 1 tables are separated from historical artifacts "
            "so different cohorts and grains are never silently mixed."
        ),
    )

    export_metadata = {
        "generated_at": generated_at,
        "evidence_type": evidence_type,
        "active_threshold": f"{active_threshold:.6f}",
        "sample_rows": str(sample_rows),
        "source_rows": str(source_rows),
    }

    table_tabs = st.tabs(
        [
            "Coverage",
            "Champion",
            "Thresholds",
            "Stability",
            "PCA",
            "K-Means",
            "DBSCAN",
            "LOF",
        ]
    )

    with table_tabs[0]:
        show_table_with_download(
            label="Validation coverage",
            data=coverage,
            file_name="ml_validation_coverage.csv",
            metadata=export_metadata,
            description="Historical audit matrix; row count is not performance.",
        )

    with table_tabs[1]:
        show_table_with_download(
            label="Controlling champion comparison",
            data=final_comparison,
            file_name="ml_champion_comparison.csv",
            metadata=export_metadata,
            description=(
                "This is the controlling source for the displayed PR-AUC, precision, "
                "recall, F1, and comparison chart."
            ),
        )
        if not final_summary.empty:
            show_table_with_download(
                label="Alternate champion summary artifact",
                data=final_summary,
                file_name="ml_champion_alternate_summary.csv",
                metadata=export_metadata,
                description=(
                    "Retained for audit only. It is not used for the top KPI because "
                    "its cohort/summary metrics differ from the controlling comparison table."
                ),
            )

    with table_tabs[2]:
        show_table_with_download(
            label="Threshold analysis",
            data=final_thresholds,
            file_name="ml_threshold_analysis.csv",
            metadata=export_metadata,
            description="Threshold trade-off rows for the final model evidence.",
        )

    with table_tabs[3]:
        show_table_with_download(
            label="Stability evidence",
            data=final_stability,
            file_name="ml_stability_evidence.csv",
            metadata=export_metadata,
            description="Repeated-seed evidence; row counts and seeds are shown explicitly.",
        )

    with table_tabs[4]:
        show_table_with_download(
            label="PCA variance",
            data=pca_variance,
            file_name="ml_pca_variance.csv",
            metadata=export_metadata,
            description="Same-sample component variance and cumulative retention.",
        )
        show_table_with_download(
            label="PCA loadings",
            data=pca_loadings,
            file_name="ml_pca_loadings.csv",
            metadata=export_metadata,
            description="Same-sample feature contributions to PC1-PC3.",
        )

    with table_tabs[5]:
        show_table_with_download(
            label="Same-sample K-Means k=1-10 grid",
            data=kmeans_grid,
            file_name="ml_kmeans_grid.csv",
            metadata=export_metadata,
            description=(
                "Controlling Package 1 selection evidence; required candidates "
                "k=3/5/7 are labelled."
            ),
        )
        show_table_with_download(
            label="Same-sample cluster business summary",
            data=cluster_business,
            file_name="ml_cluster_business_summary.csv",
            metadata=export_metadata,
            description="Cluster size and available observed value evidence.",
        )
        if not historical_kmeans.empty:
            show_table_with_download(
                label="Historical K-Means course summary",
                data=historical_kmeans,
                file_name="historical_kmeans_summary.csv",
                metadata=export_metadata,
                description=(
                    "Historical artifact with its own row count. It is retained for "
                    "audit and is not mixed into the same-sample selection chart."
                ),
            )

    with table_tabs[6]:
        show_table_with_download(
            label="Same-sample DBSCAN 3x3 grid",
            data=dbscan_grid,
            file_name="ml_dbscan_grid.csv",
            metadata=export_metadata,
            description="Exactly eps 0.5/1.0/2.0 × min_samples 3/5/10.",
        )
        show_table_with_download(
            label="Same-sample method summary",
            data=method_summary,
            file_name="ml_method_summary.csv",
            metadata=export_metadata,
            description="Selected K-Means, DBSCAN, and LOF settings on one sample.",
        )
        if not historical_dbscan.empty:
            show_table_with_download(
                label="Historical DBSCAN course summary",
                data=historical_dbscan,
                file_name="historical_dbscan_summary.csv",
                metadata=export_metadata,
                description=(
                    "Historical artifact with different parameter combinations and "
                    "row count; not used by the Package 1 parameter heatmap."
                ),
            )

    with table_tabs[7]:
        show_table_with_download(
            label="Same-sample LOF feature profile",
            data=lof_feature_profile,
            file_name="ml_lof_feature_profile.csv",
            metadata=export_metadata,
            description="Average standardized gaps between flagged and normal visitors.",
        )
        show_table_with_download(
            label="Same-sample LOF investigation queue",
            data=lof_investigation,
            file_name="ml_lof_investigation.csv",
            metadata=export_metadata,
            description="Top descriptive cases; not confirmed anomaly labels.",
        )
        if not historical_lof.empty:
            show_table_with_download(
                label="Historical LOF summary",
                data=historical_lof,
                file_name="historical_lof_summary.csv",
                metadata=export_metadata,
                description="Historical artifact retained for audit.",
            )
        show_table_with_download(
            label="Historical outlier comparison",
            data=outlier_comparison,
            file_name="historical_outlier_comparison.csv",
            metadata=export_metadata,
            description="Different methods and row counts; volume comparison only.",
        )
        show_table_with_download(
            label="Champion sensitivity after anomaly filtering",
            data=final_sensitivity,
            file_name="ml_champion_sensitivity.csv",
            metadata=export_metadata,
            description="Model sensitivity evidence retained separately from LOF proof.",
        )
